apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qdrant
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "qdrant.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ (index $.Values.service.ports 0).port }}
          protocol: TCP
        - port: {{ (index $.Values.service.ports 1).port }}
          protocol: TCP
        - port: {{ (index $.Values.service.ports 2).port }}
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              qdrant-client: "true"
          namespaceSelector:
            matchLabels:
              domino-platform: "true"
        - podSelector:
            matchLabels:
              qdrant-client: "true"
          namespaceSelector:
            matchLabels:
              domino-compute: "true"
