apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /workspaces/qdrant-storage
    type: DirectoryOrCreate
